### ISSUE TITLE
[Bug] Tools auto-fill in other fields

### ISSUE THREAD

**Issue by ThisAMJ** [RainbowwPhoenixx/p2tas-lang#16]
For example, `+2>||D` auto-fills `decel` when you hit enter.

**Comment by RainbowwPhoenixx** [comment]
Right I am aware this is a problem however this is not currently easy to detect in a nice way, however this will be fixed by #14, so I'm closing this and adding it to the list over there.

**Comment by RainbowwPhoenixx** [comment]
Actually nevermind, I'll leave it up as separate and close this once it gets implemented

**Comment by david072** [comment]
This should be closed shouldn't it @RainbowwPhoenixx?

**Comment by RainbowwPhoenixx** [comment]
Sorry for the (VERY) late response, this does not appear to be fixed. Tools will autocomplete anywhere still it seems 
![image](https://user-images.githubusercontent.com/45916137/153759269-1ad71483-46f1-46b4-8d63-746d38f820cd.png)
