### ISSUE TITLE
Can't disconnect from sar via tas integration

### ISSUE THREAD

**Issue by WhyIsEveryUsernameIsAlreadyTaken** [RainbowwPhoenixx/p2tas-lang#17]
Using v0.5.0

I'm not sure how it happened, so I don't know how you would reproduce it, but I found out that even with the game closed and having sar_tas_server set to 0, TAS integration will not disconnect. When clicking Play TAS when either sar_tas_server is set to 1 or 0, I get the error "Socket disconnected... Please connect to SAR". And when I reload the extension, TAS integration infinitely loads until I restart vsc.

Not sure if I'm at fault for this or there's already a fix for this, but I apologize for either case.

Thanks!

**Comment by RainbowwPhoenixx** [comment]
This is known about but I forgot to add it as an issue, it should be fixed by #15
