### ISSUE TITLE
[bug] Unit suffixes are recognised as errors

### ISSUE THREAD

**Issue by ThisAMJ** [RainbowwPhoenixx/p2tas-lang#22]
The language server thinks lines such as:
```
absmov -90deg
decel 0ups
```
are errors, but they work completely normally. I like to write like this for readability.

**Comment by RainbowwPhoenixx** [comment]
This is known but quite low priority as it's not really intended (much less documented) sar behavior. It could technically be considered as a parsing bug in sar that this succeeds. I'll check with mlugg if we want to make this official documented behavior, or make it not accept the script.

**Comment by mlugg** [comment]
The extension behaviour is correct, I'll modify SAR to throw a parse error in these cases.

**Comment by mlugg** [comment]
That said, I could see an argument for modifying absmov and decel to require prefixes for consistency/clarity, but there should definitely be one canonical form
