### ISSUE TITLE
[Bug] Error checking gives up after a while

### ISSUE THREAD

**Issue by ThisAMJ** [RainbowwPhoenixx/p2tas-lang#37]
![Red squiggles under top lines, but they don't continue](https://user-images.githubusercontent.com/69196954/170812573-57f5b1d3-4fd4-4e55-9067-af664abf2b25.png)

In this file, the first 750 errors are reported, then it just gives up.

To reproduce, look at any long raw file from the fullgame drive (I won't put any here for reasons).

I don't expect this to be fixed, because instead you should fix the raw error and there won't ever be 750 errors again.

**Comment by RainbowwPhoenixx** [comment]
This is very much intended. VS code has a limit on the number of diagnostics a language server can provide (although it should be set to 100?)
