### ISSUE TITLE
"Toggle Line Tick Type" deletes the line if it can't determine the tick

### ISSUE THREAD

**Issue by Cant-Even** [RainbowwPhoenixx/p2tas-lang#40]
Trying to run the "Toggle line tick type" command on a line where the extension can't determine the tick due to syntax errors will delete the line instead of taking no action.

Reproduction steps:
1. Make a script with this code (or similar invalid code under current extension)
`60>>`
`+30>>`
2. Try to run the toggle line tick type command on the second line
3. Observe how it deletes the line.

**Comment by ThisAMJ** [comment]
Still present in v1.3.0
Reproduction steps:
```
version 4
start now
0>>strafe 0deg
1>>strafe 1deg
```
Toggle tick type on the `1>>` line. If does not reproduce, try typing script by hand
