### ISSUE TITLE
[Feature] Trace tick highlight support

### ISSUE THREAD

**Issue by mlugg** [RainbowwPhoenixx/p2tas-lang#41]
Highlight the framebulk corresponding to the current trace bbox tick - requires SAR work, I can do that bit

Can use vscode.TextEditor.setDecorations on the plugin side

**Comment by RainbowwPhoenixx** [comment]
I do wonder about something, what happens when the bbox tick is in between two framebulks in the script? What about if the user edits the script?

**Comment by mlugg** [comment]
The "corresponding" framebulk is the last one run imo, since it's precisely accurate for raw data and is also the most recent update to tools. Editing the script is a more interesting point - I think you could reasonably say that if the buffer isn't the same as it was when you hit play (is there a not-stupid way you can detect this? I have a vague idea if you're unsure) to give up on the highlight altogether

**Comment by RainbowwPhoenixx** [comment]
Detecting a change is pretty trivial, I think, and these are good solutions, although maybe a bit unintuitive for someone unfamiliar, idk
It's also a pretty intrusive feature, so I'd like to do this only after the settings are put in place.
An idea I'm putting here as an refinement of the feature is that you could highlight where the active tools are set in addition to the last framebulk.
