### ISSUE TITLE
[Feature] Warn when a portal won't shoot

### ISSUE THREAD

**Issue by ThisAMJ** [RainbowwPhoenixx/p2tas-lang#52]
Because of the nature of `portalgun_fire_delay`, floating-point precision error in time addition causes *most* portals to be placed 12 ticks after the previous, but sometimes 13.

Here's a very vague implementation (not sure if this is even remotely valid ts)
```ts
let nextShot = (tick: number) => Math.ceil((tick / 60 + 0.2) * 60)
if (nextShot(tick) != tick + 12) {
    // the next shot will need 13 ticks
}
```

Here it is working in JS:
![Firefox devtools](https://user-images.githubusercontent.com/69196954/183637331-e7a09899-7960-49fb-bada-a009eee2fde9.png)

**Comment by RainbowwPhoenixx** [comment]
This is not ideal because of `start now` where the tas tick may not match the actual server tick. I would rather have this as a command that inserts a framebulk on the next tick where it thinks it would work.

**Comment by mlugg** [comment]
This doesn't work in *any* case. The variable within the game upon which the float arithmetic is done is 'curtime', whose value when starting a map varies (depending on the map and loading method) anywhere from around 0.3 to around 2.0. Without extra information, this feature is straight-up not possible.
