### ISSUE TITLE
[Feature] Add settings for the user

### ISSUE THREAD

**Issue by RainbowwPhoenixx** [RainbowwPhoenixx/p2tas-lang#6]
Add settings so the user can customize their experience:
- Choose whether or not to have the active tools display
- Create playback rate presets to automatically generate buttons in the sidebar
- Toggle asking the user for confirmation when changing fields
- Disable error checking entirely (useful when sar has implemented a feature but the extension has not been updated yet)
- others

**Comment by david072** [comment]
See https://code.visualstudio.com/api/references/contribution-points#contributes.configuration
