### ISSUE TITLE
[Bug] decel sometimes isn't being turned off properly

### ISSUE THREAD

**Issue by RainbowwPhoenixx** [RainbowwPhoenixx/p2tas-lang#8]
With certain scripts, the active tools still shows the decel tool in spite of it being explicitly turned off. The bug can be reproduced by placing the cursor on the last line of this script:
```
start now   
1>||||decel 100
2>||||decel off
3>
```

Original bug report:
https://discord.com/channels/555857702585237533/818471081027436564/926954956412563498

**Comment by david072** [comment]
I'll look into this
