### ISSUE TITLE
[Bug] comments at the end of a line confuse the active tools display

### ISSUE THREAD

**Issue by RainbowwPhoenixx** [RainbowwPhoenixx/p2tas-lang#9]
Any of the following lines will yield the tools display to be `setang (NaN ticks left)`
```
+1>||||setang 1 2 3 // comment
+1>||||setang 1 2 test
+1>||||setang 1 2 // comment
```

Another example is :
```
0>|||| // comment
```
which will display "//" as an active tool

**Comment by david072** [comment]
I'm working on this :)
